classes:
    -
        name: ".image-display"
        max_dimensions:
            height: 725
    -
        name: ".image-modal"
        max_dimensions:
            height: 500
    -
        name: ".pocket-article"
        props:
            padding_left: 0
            padding_top: 10
            padding_right: 0
            padding_bottom: 10
            margin_bottom: 25
        subdefs:
            classes:
                -
                    name: img
                    props:
                        max_width: 640
objects:
    -
        id: "intro_hydrant"
        image_url: "/img/intro_hydrant.jpg"
        location:
            top: 41
            left: 309
        dimensions:
            width: 1301
            height: 756
        classes:
            - object
            - img-round-corners
    -
        id: "intro_shoes"
        image_url: "/img/intro_shoes.png"
        location:
            top: 0
            left: 1219
        dimensions:
            width: 377
            height: 583
    -
        id: "intro_signature"
        image_url: "/img/intro_signature.png"
        location:
            top: 0
            left: 36
        dimensions:
            width: 893
            height: 381
        parallax:
            parallax_id: intro_signature_parallax
            scale: 0.04
    -
        id: "intro_tagline"
        image_url: "/img/intro_tagline.png"
        location:
            top: 460
            left: 1060
        dimensions:
            width: 592
            height: 368
        parallax:
            parallax_id: intro_tagline_parallax
            scale: 0.015
    -
        id: "great_button"
        location:
            top: 672
            left: 857
        button:
            text: "Great!"
    -
        id: pocket_articles
        dimensions:
            width: auto
            height: 700
        classes:
            - scrollfix
    -
        id: "portfolio_background"
        image_url: "/img/portfolio_background.jpg"
        location:
            top: 863
            left: 0
        dimensions:
            width: 1919
            height: 1024
        classes:
            - img-round-corners
    -
        id: "portfolio_arrows"
        image_url: "/img/portfolio_arrows.png"
        location:
            top: 867
            left: 472
        dimensions:
            width: 557
            height: 405
    -
        id: "portfolio_title_parallax02"
        image_url: "/img/portfolio_title_parallax02.png"
        location:
            top: 855
            left: 175
        dimensions:
            width: 273
            height: 83
        parallax:
            parallax_id: portfolio_parallax
            scale: 0.05
    -
        id: "portfolio_title_parallax01"
        image_url: "/img/portfolio_title_parallax01.png"
        location:
            top: 850
            left: 169
        dimensions:
            width: 288
            height: 87
        parallax:
            parallax_id: portfolio_parallax
            scale: 0.025
    -
        id: "portfolio_title"
        image_url: "/img/portfolio_title.png"
        location:
            top: 846
            left: 161
        dimensions:
            width: 303
            height: 91
    -
        id: "portfolio_neonsign01"
        image_url: "/img/portfolio_neonsign01.png"
        location:
            top: 1650
            left: 78
        dimensions:
            width: 174
            height: 214
        flicker:
            delay: 1
            min_duration: 0.05
            max_duration: 0.5
            min_opacity: 0.2
            max_opacity: 0.9
    -
        id: "portfolio_neonsign02"
        image_url: "/img/portfolio_neonsign02.png"
        location:
            top: 1513
            left: 257
        dimensions:
            width: 214
            height: 244
        flicker:
            delay: 1
            min_duration: 0.05
            max_duration: 0.5
            min_opacity: 0.2
            max_opacity: 0.9
    -
        id: "portfolio"
        location:
            top: 960
            left: 0
        dimensions:
            width: 1900
            height: 800
    -
        id: "whatido_background"
        image_url: "/img/whatido_background.jpg"
        location:
            top: 2016
            left: 203
        dimensions:
            width: 1514
            height: 862
        classes:
            - img-round-corners
    -
        id: "whatido_title_parallax02"
        image_url: "/img/whatido_title_parallax02.png"
        location:
            top: 1942
            left: 185
        dimensions:
            width: 394
            height: 101
        parallax:
            parallax_id: whatido_parallax
            scale: 0.05
    -
        id: "whatido_title_parallax01"
        image_url: "/img/whatido_title_parallax01.png"
        location:
            top: 1939
            left: 174
        dimensions:
            width: 416
            height: 107
        parallax:
            parallax_id: whatido_parallax
            scale: 0.025
    -
        id: "whatido_title"
        image_url: "/img/whatido_title.png"
        location:
            top: 1936
            left: 163
        dimensions:
            width: 438
            height: 113
    -
        id: "whatido_copy"
        container:
            id: whatido_copy_markup
            view_script: "partials/index/whatido_copy.twig.html"
        location:
            top: 2016
            left: 203
        dimensions:
            width: 1514
            height: 862
    -
        id: "whatido_copy_markup"
        location:
            top: 8%
            left: 0
        box:
            padding: 60
    -
        id: "info_background"
        image_url: "/img/info_background.jpg"
        location:
            top: 3046
            left: 226
        dimensions:
            width: 1433
            height: 897
        classes:
            - img-round-corners
    -
        id: "info_title_parallax02"
        image_url: "/img/info_title_parallax02.png"
        location:
            top: 2987
            left: 183
        dimensions:
            width: 357
            height: 134
        parallax:
            parallax_id: info_parallax
            scale: 0.05
    -
        id: "info_title_parallax01"
        image_url: "/img/info_title_parallax01.png"
        location:
            top: 2983
            left: 173
        dimensions:
            width: 377
            height: 140
        parallax:
            parallax_id: info_parallax
            scale: 0.025
    -
        id: "info_title"
        image_url: "/img/info_title.png"
        location:
            top: 2977
            left: 163
        dimensions:
            width: 397
            height: 148
    -
        id: "info_copy"
        container:
            id: info_copy_markup
            view_script: "partials/index/info_copy.twig.html"
        location:
            top: 3046
            left: 226
        dimensions:
            width: 1433
            height: 897
    -
        id: "info_copy_markup"
        location:
            top: 8%
            left: 0
        box:
            padding: 60
        props:
            text_shadow: "1px 2px 4px #000"
parallax:
    -
        id: intro_signature_parallax
        location:
            left: 530
            top: 230
    -
        id: intro_tagline_parallax
        location:
            left: 1358
            top: 678
    -
        id: portfolio_parallax
        location:
            left: 310
            top: 904
    -
        id: whatido_parallax
        location:
            left: 398
            top: 2010
    -
        id: info_parallax
        location:
            left: 348
            top: 3069
