nxmw:
    title: North By Midwest
    blurb: |
        A story about a jackass, family, the blues, and the lord almighty.
    tags:
        - Character Design
        - Illustration
    image: https://c2.staticflickr.com/2/1714/25786187901_6efd6bf47a_b.jpg
marqueeshade:
    title: Marquee Shade
    blurb: |
        As Comedy Megacorp's grip on media and entertainment continues to tighten, Carl Leander and his rag-tag group of misfits struggle to keep the club open and fight off Comedy Megacorp. By looking deep into comedy's history they are able to miraculously thwart the coporation's clutches. All the while, hilarity ensues.

        "Showbiz is a hideous bitch-godess" - George Burns.
    tags:
        - Character Design
        - Illustration
        - Story
    image: https://c1.staticflickr.com/1/624/23108862960_b5cdce3674.jpg
beepo:
    title: World of Beepo Beeparelli
    blurb: |
        A story about a japanese created italian robot who had the profession "plumber" uploaded into his main memory.
    tags:
        - Character Design
        - Illustration
        - Story
    image: https://c1.staticflickr.com/3/2439/3663515635_1c89de110c.jpg
